### ISSUE TITLE
db-config

### ISSUE THREAD

**Issue by MIJOTHY** [foundersandcoders/carrier-pigeon#126]
I quite like this file, it's pretty easy to read. 
What's the reasoning behind the `tests` function - have you thought of alternative methods to achieve the same result but without needing such a function? I'd also go for a bit better error-handling than console.logs, but ofc that's dependent on your needs.

**Comment by NataliaLKB** [comment]
@benjaminlees what is your view on the tests function. I know you are planning on rewriting the db tests this weekend.

With regards to the error handling, we are slowly converting those to `cb(err)` and for success `cb(null, orders)` so that we can then respond with a nice error message to the user. 

What do you think about that? would that be better? @benjaminlees do you think this would work for most of these situations?

**Comment by benjaminlees** [comment]
the reason for passing the tests parameter is that we use anouther db for integration tests and this allows us to use the same files but pass different db details. I do however recognise that it is not as clean and it is an issue that other developers have experienced, the reason i went for it is that it was easy to implement, but i certainly do not mind investigating other possible alternatives.

**Comment by NataliaLKB** [comment]
@MIJOTHYupdate on this issue: 

test function is removed, @benjaminlees found a better way. 
Error handling: both of us will make the appropriate adjustments as this week.

Thanks again :+1:
