### ISSUE TITLE
config.js

### ISSUE THREAD

**Issue by MIJOTHY** [foundersandcoders/carrier-pigeon#127]
Is setting `host` necessary? Also for deploying to heroku, it might be necessary to coerce `process.env.PORT` into a `Number` (Rory, Per and Jason had this issue earlier this week), though that might be a Hapi thing.

**Comment by NataliaLKB** [comment]
Thanks for the comment, but not deploying to heroku! 

I have always learned that you should go for more in the config rather than less, as you never know when you may be repeating it. Actually I think the bigger issue is that we are not using the config (where I also use the host) in the tests. But it is on my list of things to do tomorrow.

I will close this issue, but reopen if you have more questions
